"""${message}

Revision ID: ${up_revision}
Revises: ${down_revision | comma,n}
Create Date: ${create_date}

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
${imports if imports else ""}
# Generated by ``alembic revision --autogenerate`` from
# ``migrations/script.py.mako``, which is modernized from Alembic's stock
# template so revisions conform to this repo's gates as generated: modern
# union syntax rather than ``typing.Union`` (ruff UP007),
# ``collections.abc`` rather than ``typing`` for ``Sequence`` (UP035), and
# a single third-party import block (I001). The generated ``upgrade``
# body still exceeds 88 columns, which the ``migrations/versions/*.py``
# E501 per-file-ignore in ``pyproject.toml`` covers.

# revision identifiers, used by Alembic.
revision: str = ${repr(up_revision)}
down_revision: str | Sequence[str] | None = ${repr(down_revision)}
branch_labels: str | Sequence[str] | None = ${repr(branch_labels)}
depends_on: str | Sequence[str] | None = ${repr(depends_on)}


def upgrade() -> None:
    """Upgrade schema."""
    ${upgrades if upgrades else "pass"}


def downgrade() -> None:
    """Downgrade schema."""
    ${downgrades if downgrades else "pass"}
