"""initial schema: companies, company_runs, job_urls

Revision ID: 069dc393ff35
Revises:
Create Date: 2026-09-15 13:21:52.320401

"""

from __future__ import annotations

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# Generated by ``alembic revision --autogenerate`` from
# ``migrations/script.py.mako``, which is modernized from Alembic's stock
# template so revisions conform to this repo's gates as generated: modern
# union syntax rather than ``typing.Union`` (ruff UP007),
# ``collections.abc`` rather than ``typing`` for ``Sequence`` (UP035), and
# a single third-party import block (I001). The generated ``upgrade``
# body still exceeds 88 columns, which the ``migrations/versions/*.py``
# E501 per-file-ignore in ``pyproject.toml`` covers.

# revision identifiers, used by Alembic.
revision: str = "069dc393ff35"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "companies",
        sa.Column("slug", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("job_board_url", sa.String(), nullable=False),
        sa.Column("strategy", sa.String(), nullable=False),
        sa.Column("expected_jobs", sa.Integer(), nullable=True),
        sa.Column("synced_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("slug"),
    )
    op.create_table(
        "company_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_slug", sa.String(), nullable=False),
        sa.Column("batch_id", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("url_count", sa.Integer(), nullable=True),
        sa.Column("verdict", sa.String(), nullable=True),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.CheckConstraint(
            "status IN ('in_progress', 'success', 'failed')",
            name="ck_company_runs_status",
        ),
        sa.ForeignKeyConstraint(
            ["company_slug"], ["companies.slug"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("company_runs", schema=None) as batch_op:
        batch_op.create_index(
            "ix_company_runs_lookup",
            ["company_slug", "status", "finished_at"],
            unique=False,
        )

    op.create_table(
        "job_urls",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("company_slug", sa.String(), nullable=False),
        sa.Column("url", sa.String(), nullable=False),
        sa.Column("captured_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["company_slug"], ["companies.slug"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("company_slug", "url", name="uq_job_urls_company_url"),
    )
    with op.batch_alter_table("job_urls", schema=None) as batch_op:
        batch_op.create_index("ix_job_urls_company", ["company_slug"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("job_urls", schema=None) as batch_op:
        batch_op.drop_index("ix_job_urls_company")

    op.drop_table("job_urls")
    with op.batch_alter_table("company_runs", schema=None) as batch_op:
        batch_op.drop_index("ix_company_runs_lookup")

    op.drop_table("company_runs")
    op.drop_table("companies")
    # ### end Alembic commands ###
